

services:
  servicioWikis:
    image: fu17alex/modulowiki:v2.0  # Replace with the actual image name for app1
    container_name: lawiki-modulo-wiki
    networks:
      - lawiki-network
    ports:
      - "8001:8001"  # Exposing port 8000 in the container to 8001 on the host

  servicioArticulos:
    image: fu17alex/moduloarticulo:v2.0
    container_name: lawiki-modulo-articulo
    networks:
      - lawiki-network
    ports:
      - "8002:8002"

  servicioComentarios:
    image: fu17alex/modulocomentario:v1.0
    container_name: lawiki-modulo-comentario
    networks:
      - lawiki-network
    ports:
      - "8003:8003"

  servicioUsuarios:
    image: fu17alex/modulousuario:v1.0
    container_name: lawiki-modulo-usuario
    networks:
      - lawiki-network
    ports:
      - "8004:8004"

  app:
    image: fu17alex/gatewaylawiki:v1.0
    container_name: lawiki-gateway
    networks:
      - lawiki-network
    ports:
      - "8000:8000"
      

  react-app:
    image: fu17alex/frontendlawiki:v1.0
    ports:
      - "3000:80"  # React app will run on port 3000
    depends_on:
      - app  # Optional: Ensure React waits for backend services
    networks:
      - lawiki-network  # If backend services are on a custom network

networks:
  lawiki-network:
    driver: bridge
